import { readable, writable } from "svelte/store";



export const itemsList = readable([{"value":"ref10","label":"ref10"},{"value":"ref11","label":"ref11"},{"value":"ref12","label":"ref12"},{"value":"ref13","label":"ref13"},{"value":"ref14","label":"ref14"},{"value":"ref15","label":"ref15"},{"value":"ref16","label":"ref16"},{"value":"ref7","label":"ref7"},{"value":"ref8","label":"ref8"},{"value":"ref9","label":"ref9"},{"value":"people","label":"people"},{"value":"elderSum","label":"elderSum"},{"value":"marriedSum","label":"marriedSum"},{"value":"elderPerc","label":"elderPerc"},{"value":"marriedPerc","label":"marriedPerc"},{"value":"ageMedian","label":"ageMedian"},{"value":"seven_n","label":"seven_n"},{"value":"univPerc","label":"univPerc"},{"value":"countytown.id","label":"countytown.id"},{"value":"tks.sum","label":"tks.sum"},{"value":"kmt.rate","label":"kmt.rate"},{"value":"dpp.rate","label":"dpp.rate"},{"value":"other.rate","label":"other.rate"},{"value":"voteRateref10","label":"voteRateref10"},{"value":"voteRateref11","label":"voteRateref11"},{"value":"voteRateref12","label":"voteRateref12"},{"value":"voteRateref13","label":"voteRateref13"},{"value":"voteRateref14","label":"voteRateref14"},{"value":"voteRateref15","label":"voteRateref15"},{"value":"voteRateref16","label":"voteRateref16"},{"value":"voteRateref7","label":"voteRateref7"},{"value":"voteRateref8","label":"voteRateref8"},{"value":"voteRateref9","label":"voteRateref9"},{"value":"validRateref10","label":"validRateref10"},{"value":"validRateref11","label":"validRateref11"},{"value":"validRateref12","label":"validRateref12"},{"value":"validRateref13","label":"validRateref13"},{"value":"validRateref14","label":"validRateref14"},{"value":"validRateref15","label":"validRateref15"},{"value":"validRateref16","label":"validRateref16"},{"value":"validRateref7","label":"validRateref7"},{"value":"validRateref8","label":"validRateref8"},{"value":"validRateref9","label":"validRateref9"},{"value":"headhouse_F","label":"headhouse_F"},{"value":"headhouse_M","label":"headhouse_M"},{"value":"headhouse_maleperc","label":"headhouse_maleperc"},{"value":"COUNTYCODE","label":"COUNTYCODE"},{"value":"dist2nu1","label":"dist2nu1"},{"value":"dist2nu2","label":"dist2nu2"},{"value":"dist2nu3","label":"dist2nu3"},{"value":"min_dist2nu","label":"min_dist2nu"}]
);


export const selectedVar = writable(['nothing']);
